services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_API_URL: http://45.90.237.135:3001
    ports:
      - "8080:4321"
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./api/olivaxi.db:/app/olivaxi.db
    environment:
      - GROQ_KEY=${GROQ_KEY}
      - GEMINI_KEY=${GEMINI_KEY}
      - OPENROUTER_KEY=${OPENROUTER_KEY}
    restart: unless-stopped